Repository thoth-station/s2i-thoth, pull requests merged in 2019-10, with the labels that each got.

#18 Exit with one on commands which should cause the build to fail
  assemble
Labels: approved, size/S

#19 S2I builder image using Python3.7
  fedora30-py37/Dockerfile
  fedora30-py37/s2i_assemble.patch
Labels: size/M

#21 Provide an option which will fallback to repo Pipfile.lock if Thoth's advises fail
  README.rst
  assemble
Labels: approved, size/S

#22 Export variables used in sub-processes
  assemble
Labels: approved, do-not-merge/needs-rebase, size/XS

#23 Hotfix to avoid cache
  README.rst
  ubi8-py36/Dockerfile
Labels: approved, do-not-merge/needs-rebase, size/XS

#24 quay status badge
  README.rst
Labels: approved, do-not-merge/needs-rebase, size/XS
