Repository thoth-station/s2i-thoth, pull requests merged in 2019-08, with the labels that each got.

#1 Add s2i-thoth-ubi8-py36
  README.rst
  assemble
  build_all.sh
  ubi8-py36/Dockerfile
Labels: size/L

#2 Automatically build in quay.io on merges to master
  README.rst
  ubi8-py36/Dockerfile
Labels: size/S

#4 Remove old bits
  build_all.sh
  ubi8-py36/Dockerfile
Labels: size/S

#3 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#5 Link to Thamos for Thamos related configuration options
  README.rst
Labels: size/XS

#7 Add GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M

#8 Print message if Thoth recomendations are not activated
  assemble
Labels: approved, size/XS

#9 State how to import image into OpenShift's registry
  README.rst
Labels: approved, size/XS

#12 Added zuul config file
  .zuul.yaml
Labels: approved, size/XS

#13 Pre-install Pipenv into base image
  ubi8-py36/Dockerfile
  ubi8-py36/s2i_assemble.patch
Labels: approved, size/M, size/XS

#15 Fix permission issues when installing into virtual env
  ubi8-py36/Dockerfile
Labels: size/XS

#16 [WIP] added a changelog and a few updates
  .coafile
  CHANGELOG.md
  ubi8-py36/Dockerfile
Labels: approved, size/M, size/S, size/XS
