Repository thoth-station/s2i-thoth, pull requests merged in 2020-02, with the labels that each got.

#35 Create .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#36 Add section for Thoth runtime environment to .thoth.yaml
  .thoth.yaml
Labels: size/S

#37 Start using micropipenv in s2i-thoth container images
  f31-py37/Dockerfile
  f31-py37/s2i_assemble.patch
  ubi8-py36/Dockerfile
  ubi8-py36/s2i_assemble.patch
Labels: size/M

#38 Bump micropipenv version to respect fixes in new release
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: size/XS

#40 Bump micropipenv version
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved, size/XS
