Repository thoth-station/s2i-thoth, pull requests merged in 2020-11, with the labels that each got.

#87 Bump micropipenv and thamos versions
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#88 Bump versions of micropipenv and thamos
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#89 Version v0.20.1
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#92 Use pip==20.1.1 in the base images
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/XS

#93 update to the latest base images, and thamos to 1.4.0
  RELEASES.rst
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  releasenotes/notes/RHBA-2020:3156_Bug_Fix_Advisory-f831cf9b62e07a6d.yaml
  releasenotes/notes/tooling-update-63874fa8f8c688da.yaml
  releasenotes/notes/ubi8-base-update-542460957836ef10.yaml
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/L

#94 Adjust assemble scripts as micropipenv is in UBI images
  ubi8-py36/s2i_assemble.patch
  ubi8-py38/s2i_assemble.patch
Labels: approved, size/L

#95 Version 0.21.1
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/XS

#97 Bump thamos to 1.5.1
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/XS

#96 Use thamos install as an installation method
  README.rst
  assemble
  f31-py37/s2i_assemble.patch
  f32-py38/s2i_assemble.patch
  ubi8-py36/s2i_assemble.patch
  ubi8-py38/s2i_assemble.patch
Labels: approved, size/L

#98 Fix patch set so chunks merge
  f31-py37/s2i_assemble.patch
  f32-py38/s2i_assemble.patch
  ubi8-py36/s2i_assemble.patch
  ubi8-py38/s2i_assemble.patch
Labels: approved, size/S

#101 Version 0.21.2
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/XS
