Repository thoth-station/s2i-thoth, pull requests merged in 2020-04, with the labels that each got.

#57 updated thamos and micropipenv version
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved, size/S

#58 Bump micropipenv version to 0.1.5
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved, size/XS

#60 Print Thoth's configuration file in JSON format instead of YAML
  assemble
Labels: size/XS

#61 Bump thamos to 0.9.4
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved, size/XS

#62 Print Thoth s2i builder image version to logs
  assemble
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved

#64 Print adviser log on error if dry run was not set
  assemble
Labels: approved, size/S

#63 Prepare s2i environment to be run in an OpenShift cluster
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: approved, size/XS

#65 Bump thamos to 0.10.0
  f31-py37/Dockerfile
  ubi8-py36/Dockerfile
Labels: size/XS

#67 Obtain adviser logs only if the request was submitted
  assemble
Labels: approved, size/XS

#66 Fix handling requirements.txt for s2i-thoth
  f31-py37/s2i_assemble.patch
  ubi8-py36/s2i_assemble.patch
Labels: approved, size/M
