Repository thoth-station/s2i-thoth, pull requests merged in 2021-02, with the labels that each got.

#135 updated requirements.txt fixing the missing packages
  requirements.txt
Labels: approved, size/M

#136 maintain separate requirements based on the environment
  f31-py37/Dockerfile
  f31-py37/requirements.txt
  f32-py38/Dockerfile
  f32-py38/requirements.txt
  ubi8-py36/Dockerfile
  ubi8-py36/requirements.txt
  ubi8-py38/Dockerfile
  ubi8-py38/requirements.txt
Labels: approved, size/XXL

#137 Bump the version to v0.24.2
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/XS

#139 Update Thamos and provide requirements.in files
  f31-py37/requirements.in
  f31-py37/requirements.txt
  f32-py38/requirements.in
  f32-py38/requirements.txt
  ubi8-py36/requirements.in
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.in
  ubi8-py38/requirements.txt
Labels: approved, lgtm, size/XXL

#140 Update thamos to v1.10.0
  f31-py37/requirements.txt
  f32-py38/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/S

#142 Dependency update
  f31-py37/requirements.txt
  f32-py38/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/M

#147 Update dependencies in Thoth s2i container images
  f31-py37/requirements.txt
  f32-py38/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/L
