Repository thoth-station/s2i-thoth, pull requests merged in 2021-07, with the labels that each got.

#190 Allow users to generate thoth configuration during the build process
  README.rst
  assemble
Labels: approved, size/XS

#193 Provide a way to disable all the Thoth features
  README.rst
  assemble
Labels: approved, lgtm, size/S

#197 add Ubi8 py39
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prow.yaml
  README.rst
  f32-py38/Dockerfile
  f34-py39/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
  ubi8-py39/Dockerfile
  ubi8-py39/requirements.in
  ubi8-py39/requirements.txt
  ubi8-py39/s2i_assemble.patch
Labels: size/L

#200 Fix issue with thoth config not generated from template
  assemble
Labels: approved, size/S

#199 Update all requirements.txt to have new thamos version
  f32-py38/Dockerfile
  f32-py38/requirements.txt
  f34-py39/Dockerfile
  f34-py39/requirements.txt
  ubi8-py36/Dockerfile
  ubi8-py36/requirements.txt
  ubi8-py38/Dockerfile
  ubi8-py38/requirements.txt
  ubi8-py39/Dockerfile
  ubi8-py39/requirements.txt
Labels: approved, size/XXL

#205 Add an example on how to build container images locally
  README.rst
Labels: approved, size/S

#206 Fix operator used
  assemble
Labels: approved, size/XS

#207 Remove f32-py38
  f32-py38/Dockerfile
  f32-py38/requirements.in
  f32-py38/requirements.txt
  f32-py38/s2i_assemble.patch
Labels: approved, size/XL

#208 Fix syntax error on build
  f34-py39/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
  ubi8-py39/requirements.txt
Labels: size/L

#211 Bump thamos to v1.20.0
  f34-py39/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/L

#210 Do not use curl but copy requirements.txt
  f34-py39/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#212 Fix up the assemble script with the s2i-assemble
  f34-py39/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
  ubi8-py39/Dockerfile
Labels: approved, size/S
