Repository thoth-station/s2i-thoth, pull requests merged in 2021-04, with the labels that each got.

#164 Link s2i-example repository in the README file
  README.rst
Labels: approved

#153 Explicitly provide micropipenv env vars to s2i
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#168 Bump thamos to v1.18.0
  f31-py37/requirements.txt
  f32-py38/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/XXL

#174 Bump thamos to v1.18.1
  f31-py37/requirements.txt
  f32-py38/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: size/M

#176 Disable update manager
  .thoth.yaml
  requirements.in
  requirements.txt
Labels: approved, size/M

#175 ci updates include prow, aicoe-ci and pre-commit
  .aicoe-ci.yaml
  .github/CODEOWNERS
  .pre-commit-config.yaml
  .prow.yaml
  README.rst
  f31-py37/s2i_assemble.patch
  f32-py38/s2i_assemble.patch
  ubi8-py36/s2i_assemble.patch
  ubi8-py38/s2i_assemble.patch
Labels: approved, size/M
