Repository thoth-station/s2i-thoth, pull requests merged in 2021-06, with the labels that each got.

#184 Add f34-py39 Thoth s2i
  README.rst
  f34-py39/Dockerfile
  f34-py39/requirements.in
  f34-py39/requirements.txt
  f34-py39/s2i_assemble.patch
Labels: approved, size/XL

#185 Bump upto version v0.29.0
  f31-py37/Dockerfile
  f32-py38/Dockerfile
  f34-py39/Dockerfile
  ubi8-py36/Dockerfile
  ubi8-py38/Dockerfile
Labels: approved, size/S

#192 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS
