Repository thoth-station/s2i-thoth, pull requests merged in 2022-09, with the labels that each got.

#256 Fix README.rst typo
  README.rst
Labels: size/XS, approved, lgtm

#252 creating ubi9-py39 overlay
  ubi9-py39/Dockerfile
  ubi9-py39/requirements.in
  ubi9-py39/requirements.txt
  ubi9-py39/s2i_assemble.patch
Labels: approved, size/XL, lgtm

#263 Update the Readme with s2i-thoth-ubi9-py39
  README.rst
Labels: size/M, approved
