Repository thoth-station/s2i-thoth, pull requests merged in 2022-04, with the labels that each got.

#236 Use bash, always
  update-requirements.sh
Labels: size/XS, approved

#237 Update dependencies in all Thoth s2i
  f34-py39/requirements.txt
  f35-py310/requirements.txt
  ubi8-py36/requirements.txt
  ubi8-py38/requirements.txt
Labels: approved, size/XXL

#238 update churn
  f34-py39/requirements.txt
  f35-py310/requirements.txt
  ubi8-py36/Dockerfile
  ubi8-py36/requirements.txt
  ubi8-py38/Dockerfile
  ubi8-py38/requirements.txt
  ubi8-py39/Dockerfile
  ubi8-py39/requirements.txt
Labels: size/XXL
